### PR TITLE
Add support for concolic execution (ConDpor)

### PR DESCRIPTION
**Pull request by btwael**
This introduces concolic execution support (ConDpor) for TraceForge.

The support is by default disabled and to be enabled using
```rust
Config::builder().with_symbolic(true).build()
```
When enabled, TraceForge records symbolic variables and symbolic constraint evaluations in the execution graph.
We rely on Z3 to check path feasibility, and uses those checks to guide forward and backward revisits.

## API

The symbolic API lives under `traceforge::symbolic`:
- `symbolic::fresh_int()` creates a fresh symbolic integer.
- `symbolic::fresh_bool()` creates a fresh symbolic boolean.
- `symbolic::eval(expr)` evaluates a symbolic boolean expression as a branch decision and schedules a forward revisit when both outcomes are feasible.
- `symbolic::assume(expr)` blocks the current execution when the assumption is infeasible.
- `symbolic::assert(expr)` reports a feasible assertion failure, or records it and keeps exploring when `with_keep_going_after_error(true)` is enabled.

Symbolic values are represented as `SymExpr`. Operations are defined directly on `SymExpr`, so expressions can be composed before being passed to `symbolic::eval`, `symbolic::assume`, or `symbolic::assert`.
Symbolic expressions support boolean operators, comparisons, and integer arithmetic, including `and`, `or`, `not`, `implies`, `eq`, `gt`, `ge`, `lt`, `le`, `+`, `-`, `*`, `/`, and `%`.

Support for other theories can be added incrementally as needed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rupakm — COMMENTED** [review]
Review of the concolic execution support. Code is cleanly factored into `traceforge/src/symbolic/{mod,expr,solver}.rs` plus two new label kinds in `event_label.rs` and integration in `must.rs`. A few items below — the first is a build/CI blocker.

## Correctness / blockers

- **`z3` is added as a mandatory `[dependency]`, not feature-gated.** This pulls in `z3-sys`, which links against the system `libz3` and requires `z3.h` at build time. `cargo check` on this branch fails in an environment matching the project's CI (`wrapper.h:1:10: fatal error: 'z3.h' file not found`), and the PR doesn't update `.github/workflows/test.yml` to install z3 or enable the `z3-sys` `bundled` feature. Minimum bar: gate behind a `symbolic` Cargo feature (and document it), or update CI to install `libz3-dev`. As-is, merging breaks the build for anyone without z3 installed and breaks the CI added in #11.
- **`handle_constraint_eval` when both branches are infeasible** (`!true_sat && !false_sat`): it adds the label with `branch_taken = true` (the constructor default) and stops. The recorded label says we took the true branch, but no constraint is actually pushed to the path solver. This can confuse later replay/printing if the execution graph is inspected. Either skip recording, or set `branch_taken` to a sentinel that's not interpreted as a real direction.
- **`is_maximal_constraint` returns `false` when both branches are infeasible** under a hypothetical revisit view. Returning `false` in an "impossible" state is defensive but worth a comment explaining the reasoning, and a `debug_assert!` so the case is detectable in tests.

## Performance

`symbolic_solver_for_graph` rebuilds a fresh Z3 solver and replays *all* `ConstraintEval` labels from the entire graph on every backward-revisit feasibility check (`symbolic_backward_revisit_is_sat`) and every constraint-maximality check (`is_maximal_constraint`). For non-trivial programs this will dominate runtime. Standard fixes: cache Z3 ASTs per-`SymExpr`, and use `solver.push()/pop()` against the running path solver rather than reconstructing it. Worth flagging as a follow-up even if not blocking.

## Quality / simplification

- `traceforge/src/symbolic/expr.rs`: method names mix conventions — `mult`, but `+`/`-`/`*` are also implemented via `std::ops`. Drop the duplicates (`sub`, `mult`, `div`, `rem`) and just rely on the operator impls; rename `mult` → `mul` if you keep one.
- `pub fn eq(self, ...)` on `SymExpr` shadows `PartialEq::eq` — readable today but a footgun. Consider `eq_sym`/`equals` or document.
- Inside `symbolic/mod.rs`, `pub fn assert(...)` calls `crate::assert(ok)` — the dual `assert` shadowing is fragile; consider a clearer name.
- `handle_constraint_eval` shadows `pos` mid-function — minor confusion.
- Cargo.toml/cons.rs/exec_graph.rs/must.rs include unrelated whitespace cleanups that bloat the diff. Splitting those into a separate commit would help.
- `ConstraintKind` has only one variant `Branch`. Either drop the enum until needed, or note the intended future variants.

## Tests

Coverage of feature combinations is decent (forward revisit, both-feasible branch, `keep_going_after_error`, ordering-bug exposure). Gaps:

- No test for `assume(unsatisfiable)` actually blocking. The existing test only assumes a feasible guard.
- No test exercises the `!true_sat && !false_sat` path in `handle_constraint_eval`.
- No focused test for replay correctness across a constraint's flipped `branch_taken` (covered indirectly by `forward_revisit_explores_both_branch_outcomes`, but a 2-exec direct test would be more diagnostic).
- `symbolic_expr_supports_arithmetic_and_boolean_helpers` only asserts `stats.execs > 0` — fragile and doesn't verify the encoding.

Nice work overall; the symbolic layer is clean. The CI/build gating is the main thing that needs to land before merge.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by btwael** [comment]
@rupakm, I addressed most of the review points. A few notes:
- Added `libz3-dev` to the CI workflow;
- Changed the `!true_sat && !false_sat` to panic instead of stopping the model checker. This case should be unreachable, it is a sanity check.
- Added a test for `symbolic::assume` with an unsatisfiable constraint, checking that it blocks the execution.
- Renamed the symbolic equality helper from `eq` to `equals` to avoid confusion with `PartialEq::eq`.
- Regarding performance: I agree this may become expensive and is worth a follow-up. Reusing `push`/`pop` for these graph-view checks is not straightforward because backward-revisit feasibility and maximality are evaluated on derived execution-graph views, not just the current linear path. An incremental implementation would need to cache the exact symbolic constraints available at each graph point/view, which can become large.
(I discussed this with Mohammed; he experimented with similar ideas in JMC while implementing ConDPOR, but the results were not compelling enough.)

**Comment by rupakm** [comment]
@btwael performance: let's revisit in the future if this becomes an issue

File: traceforge/src/must.rs [hunk 1]
```diff
@@ -301,6 +312,13 @@ impl Must {
         self.current.rqueue.clear();
         self.states.clear();
         self.current.graph = eg;
+        self.symbolic_solver.reset();
+    }
+
+    pub(crate) fn next_symbolic_var_id(&mut self) -> SymVarId {
```
Comment (rupakm) [inline traceforge/src/must.rs]: These symbolic IDs depend on the order in which threads call `fresh_*` in this execution. `begin_execution` resets the counter to 1, and `handle_symbolic_var` validates the stored ID during replay, so a revisit that schedules two existing threads in a different order can assign `SymVarId(1)` to the other thread and trip the deterministic replay check, or worse, associate constraints with the wrong variable. The ID needs to be stable for the event being replayed, e.g. derived from the event/thread position or recovered from the graph when `is_replay(pos)` is true, rather than from a global schedule-order counter.

File: traceforge/src/symbolic/expr.rs [hunk 2]
```diff
@@ -0,0 +1,442 @@
...
+            })
+            .unwrap_or_else(|| panic!("unknown bound variable `{name}`"))
+    }
+
+    pub fn forall<const N: usize>(
+        &self,
+        vars: [(&str, SymSort); N],
+        body: impl FnOnce(&BoundVars) -> SymExpr,
+    ) -> SymExpr {
+        quantified_with_scopes(true, &self.scopes, vars, body)
```
Comment (rupakm) [inline traceforge/src/symbolic/expr.rs]: Nested quantifiers can mis-bind captured outer variables. A value returned by `outer.get("b")` has `BoundVarId { depth: 0, ... }`; if it is captured and used inside this nested `forall`/`exists`, `compile_quantifier` pushes a new scope and that depth 0 now resolves to the inner variable. For example, `exists b: Bool. forall c: Bool. b == c` can be encoded as `let b = outer.get("b"); outer.forall([("c", Bool)], |inner| b.clone().equals(inner.get("c")))`, but it compiles like `forall c. c == c`. Either adjust captured depths when entering a nested scope or make the API prevent carrying `SymExpr::BoundVar` values across quantifier builders.

**Review by rupakm — CHANGES_REQUESTED** [review]
I found two correctness issues in the symbolic support that should be fixed before merging: symbolic variable IDs are schedule-order dependent, and captured outer quantified variables can be rebound incorrectly under nested quantifiers.

File: traceforge/src/must.rs (hunk 1 above)
Comment (btwael) [reply traceforge/src/must.rs]: I agree: I added a test that catches exactly this; I fixed it by using the `SymbolicVar` event position (thread id and event index) as stable identity for `SymVarId`.

File: traceforge/src/symbolic/expr.rs (hunk 2 above)
Comment (btwael) [reply traceforge/src/symbolic/expr.rs]: Fixed; An alternative solution is in a Z3-style API: create the quantified symbols first, then pass them explicitly to `forall`/`exists` as the variables to bind. This avoids the capture issue because variables are explicit objects, not resolved through nested scopes. The tradeoff in our setting is that declaring them like normal symbolic variables would also create graph events for them, even though quantified variables are local to a formula.
